// WARNING: This file is auto-generated by app_target_default_entrypoint CMake
// command. Don't edit it. Instead provide your own main.cpp and don't use
// app_target_default_entrypoint.

#include "DynamicPageLayout.h"
#include "widgetmanager.h"

#include <qul/application.h>
#include <qul/qul.h>
#ifdef APP_SAFE_RENDERER
#include <qul/imagedecoders/saferendererbitmapdecoder.h>
#endif
#ifdef TVII_PLATFORM
#include "board_config.h"
#endif

int main ()
{

    Qul::initHardware();

#ifdef APP_SAFE_RENDERER
    static SafeRendererBitmapDecoder srbDecoder;
    Qul::Application::addImageDecoder(&srbDecoder);
#endif

#ifdef TVII_PLATFORM
    ConfigureBoard();
#endif

    Qul::initPlatform();

    // Initialize the sngleton objects to keep the widget layout ready
    WidgetManager::instance();

    Qul::Application _qul_app;
    static struct ::DynamicPageLayout _qul_item;
    _qul_app.setRootItem(&_qul_item);
#ifdef APP_DEFAULT_UILANGUAGE
    _qul_app.settings().uiLanguage.setValue(APP_DEFAULT_UILANGUAGE);
#endif
    _qul_app.exec();
    return 0;
}
